name: Release

# Events that trigger this workflow
on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please 🎉
        id: release
        uses: google-github-actions/release-please-action@v3.5.0
        with:
          token: ${{ secrets.ADMIN_REPO_TOKEN }}
          release-type: simple
          package-name: telestion-terminal-client

      - name: Checkout 📥
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up JDK 16 💿
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: '16'
          java-package: jdk

      - name: Install dependencies 📚
        if: ${{ steps.release.outputs.release_created }}
        run: chmod +x gradlew && ./gradlew

      - name: Publish packages 🗜
        if: ${{ steps.release.outputs.release_created }}
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_MAVEN_SUBKEYID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_MAVEN_SUBKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_MAVEN_SUBKEY_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
